name: teacher_mobile_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  easy_localization: ^3.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_otp_text_field: ^1.1.1
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  get: ^4.6.5
  google_fonts: ^5.1.0
  intl_phone_field: ^3.2.0
  lottie: ^2.5.0
  persistent_bottom_nav_bar_v2: ^4.2.8
  pin_code_text_field: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/img/
    - assets/lang/
    - assets/icon/profile/