name: teacher_mobile_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  back_button_interceptor: ^7.0.0
  blur: ^3.1.0
  easy_localization: ^3.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_otp_text_field: ^1.1.1
  flutter_svg: ^2.0.7
  flutter_video_info: ^1.3.1
  get: ^4.6.5
  google_fonts: ^5.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  intl_phone_field: ^3.2.0
  lottie: ^2.5.0
  pin_code_text_field: ^1.8.0
  shared_preferences: ^2.2.0
  video_thumbnail: ^0.5.2
  flutter_screenutil: 5.8.4
  video_player: ^2.7.1
  flutter_tex: ^4.0.3+4
  rounded_background_text: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/img/
    - assets/lang/
    - assets/lottie/
    - assets/icon/profile/
    - assets/
